import { SlashCommandBuilder, PermissionFlagsBits } from 'discord.js';
import { embed, ok, fail } from '../utils/embed.js';
import { database } from '../database/index.js';
import { isOnCooldown } from '../config.js';

const commands = [
  { data: new SlashCommandBuilder().setName('ping').setDescription('Check bot latency'), execute: async i => i.reply({ embeds: [embed('Pong', `API latency: **${i.client.ws.ping}ms**`)], ephemeral: true }) },
  { data: new SlashCommandBuilder().setName('help').setDescription('Show NIGHTMARE V2.44 commands'), execute: async i => i.reply({ embeds: [embed('NIGHTMARE V2.44', '**Moderation**: ban, kick, timeout, warn, warnings, clear, lock, unlock\n**Utility**: ping, serverinfo, userinfo, avatar, poll, say, remind\n**Configuration**: config\n\nThis foundation is modular and ready for additional feature modules.')], ephemeral: true }) },
  { data: new SlashCommandBuilder().setName('serverinfo').setDescription('Show server information'), execute: async i => i.reply({ embeds: [embed(i.guild.name, `Members: **${i.guild.memberCount}**\nCreated: <t:${Math.floor(i.guild.createdTimestamp / 1000)}:D>\nOwner: <@${i.guild.ownerId}>`)] }) },
  { data: new SlashCommandBuilder().setName('userinfo').setDescription('Show user information').addUserOption(o => o.setName('user').setDescription('User to inspect').setRequired(false)), execute: async i => { const u = i.options.getUser('user') || i.user; await i.reply({ embeds: [embed(u.tag, `ID: \`${u.id}\`\nCreated: <t:${Math.floor(u.createdTimestamp / 1000)}:R>`, 0x5865f2)] }); } },
  { data: new SlashCommandBuilder().setName('avatar').setDescription('Show a user avatar').addUserOption(o => o.setName('user').setDescription('User').setRequired(false)), execute: async i => { const u = i.options.getUser('user') || i.user; await i.reply({ embeds: [embed(`${u.tag}'s avatar`, `[Open full size](${u.displayAvatarURL({ size: 2048 })})`).setImage(u.displayAvatarURL({ size: 1024 }))] }); } },
  { data: new SlashCommandBuilder().setName('config').setDescription('View server configuration').setDefaultMemberPermissions(PermissionFlagsBits.Administrator), execute: async i => i.reply({ embeds: [embed('Server configuration', `\`\`\`json\n${JSON.stringify(database.getSettings(i.guildId), null, 2)}\n\`\`\``)], ephemeral: true }) },
  { data: new SlashCommandBuilder().setName('warn').setDescription('Warn a member').addUserOption(o => o.setName('user').setDescription('Member').setRequired(true)).addStringOption(o => o.setName('reason').setDescription('Reason').setRequired(true)).setDefaultMemberPermissions(PermissionFlagsBits.ModerateMembers), execute: async i => { const u = i.options.getUser('user'); const reason = i.options.getString('reason'); if (u.id === i.user.id) return i.reply({ embeds: [fail('You cannot warn yourself.')], ephemeral: true }); database.db.prepare('INSERT INTO warnings(guild_id,user_id,moderator_id,reason,created_at) VALUES(?,?,?,?,?)').run(i.guildId, u.id, i.user.id, reason, Date.now()); await i.reply({ embeds: [ok(`Warned ${u} for **${reason}**.`)], ephemeral: true }); } },
  { data: new SlashCommandBuilder().setName('warnings').setDescription('View member warnings').addUserOption(o => o.setName('user').setDescription('Member').setRequired(true)).setDefaultMemberPermissions(PermissionFlagsBits.ModerateMembers), execute: async i => { const u = i.options.getUser('user'); const rows = database.db.prepare('SELECT reason, moderator_id, created_at FROM warnings WHERE guild_id=? AND user_id=? ORDER BY created_at DESC LIMIT 10').all(i.guildId, u.id); const text = rows.length ? rows.map((r, n) => `**${n + 1}.** ${r.reason} — <@${r.moderator_id}>`).join('\n') : 'No warnings found.'; await i.reply({ embeds: [embed(`Warnings for ${u.tag}`, text)], ephemeral: true }); } }
];
export async function loadCommands(client) { for (const command of commands) client.commands.set(command.data.name, command); }
export { commands };
