import { SlashCommandBuilder, PermissionFlagsBits, ChannelType, ButtonBuilder, ButtonStyle, ActionRowBuilder } from 'discord.js';
import { embed, ok, fail } from '../utils/embed.js';
import { database } from '../database/index.js';
const admin = PermissionFlagsBits.Administrator;
const mod = PermissionFlagsBits.ModerateMembers;
const reason = i => i.options.getString('reason') || 'No reason provided';
const target = i => i.options.getMember('user');
function guard(i, member) { if (!member) return 'Member not found.'; if (member.id === i.user.id) return 'You cannot target yourself.'; if (member.id === i.guild.ownerId) return 'The server owner cannot be targeted.'; if (i.member.id !== i.guild.ownerId && member.roles.highest.position >= i.member.roles.highest.position) return 'Your highest role must be above the target.'; if (member.roles.highest.position >= i.guild.members.me.roles.highest.position) return 'My highest role must be above the target.'; return null; }
function moderation(name, description, action) { return { data: new SlashCommandBuilder().setName(name).setDescription(description).addUserOption(o=>o.setName('user').setDescription('Member').setRequired(true)).addStringOption(o=>o.setName('reason').setDescription('Reason').setRequired(false)).setDefaultMemberPermissions(mod), execute: async i => { const m=target(i), issue=guard(i,m); if(issue)return i.reply({embeds:[fail(issue)],ephemeral:true}); const r=reason(i); await action(i,m,r); database.case(i.guildId,m.id,i.user.id,name,r); return i.reply({embeds:[ok(`${name} applied to ${m}.`)],ephemeral:true}); } }; }
const commands = [
 {data:new SlashCommandBuilder().setName('ping').setDescription('Check bot latency'),execute:i=>i.reply({embeds:[embed('Pong',`API latency: **${i.client.ws.ping}ms**`)],ephemeral:true})},
 {data:new SlashCommandBuilder().setName('help').setDescription('Show commands'),execute:i=>i.reply({embeds:[embed('NIGHTMARE V2.44','Moderation, tickets, giveaways, configuration, verification, and owner tools.')]})},
 {data:new SlashCommandBuilder().setName('serverinfo').setDescription('Show server information'),execute:i=>i.reply({embeds:[embed(i.guild.name,`Members: **${i.guild.memberCount}**\nOwner: <@${i.guild.ownerId}>`)]})},
 {data:new SlashCommandBuilder().setName('userinfo').setDescription('Show user information').addUserOption(o=>o.setName('user').setDescription('User').setRequired(false)),execute:i=>{const u=i.options.getUser('user')||i.user;return i.reply({embeds:[embed(u.tag,`ID: \`${u.id}\``)]})}},
 moderation('ban','Ban a member',(i,m,r)=>m.ban({reason:r})), moderation('kick','Kick a member',(i,m,r)=>m.kick(r)),
 {data:new SlashCommandBuilder().setName('timeout').setDescription('Timeout a member').addUserOption(o=>o.setName('user').setDescription('Member').setRequired(true)).addIntegerOption(o=>o.setName('duration').setDescription('Seconds').setMinValue(1).setMaxValue(2419200).setRequired(true)).addStringOption(o=>o.setName('reason').setDescription('Reason')),execute:async i=>{const m=target(i),issue=guard(i,m);if(issue)return i.reply({embeds:[fail(issue)],ephemeral:true});await m.timeout(i.options.getInteger('duration')*1000,reason(i));return i.reply({embeds:[ok('Member timed out.')],ephemeral:true})}},
 {data:new SlashCommandBuilder().setName('clear').setDescription('Delete recent messages').addIntegerOption(o=>o.setName('amount').setDescription('1-100').setMinValue(1).setMaxValue(100).setRequired(true)).setDefaultMemberPermissions(PermissionFlagsBits.ManageMessages),execute:async i=>{const n=await i.channel.bulkDelete(i.options.getInteger('amount'),true);return i.reply({embeds:[ok(`Deleted **${n.size}** messages.`)],ephemeral:true})}},
 {data:new SlashCommandBuilder().setName('config').setDescription('Configure server').setDefaultMemberPermissions(admin)
  .addSubcommand(s=>s.setName('view').setDescription('View settings'))
  .addSubcommand(s=>s.setName('welcome').setDescription('Set welcome channel').addChannelOption(o=>o.setName('channel').setDescription('Text channel').addChannelTypes(ChannelType.GuildText).setRequired(true)))
  .addSubcommand(s=>s.setName('goodbye').setDescription('Set goodbye channel').addChannelOption(o=>o.setName('channel').setDescription('Text channel').addChannelTypes(ChannelType.GuildText).setRequired(true)))
  .addSubcommand(s=>s.setName('logs').setDescription('Set logs channel').addChannelOption(o=>o.setName('channel').setDescription('Text channel').addChannelTypes(ChannelType.GuildText).setRequired(true)))
  .addSubcommand(s=>s.setName('moderation').setDescription('Enable or disable moderation').addBooleanOption(o=>o.setName('enabled').setDescription('Enabled').setRequired(true)))
  .addSubcommand(s=>s.setName('automod').setDescription('Enable or disable automod').addBooleanOption(o=>o.setName('enabled').setDescription('Enabled').setRequired(true)))
  .addSubcommand(s=>s.setName('tickets').setDescription('Set ticket staff role').addRoleOption(o=>o.setName('role').setDescription('Role').setRequired(true)))
  .addSubcommand(s=>s.setName('verification').setDescription('Set verification roles').addRoleOption(o=>o.setName('verified_role').setDescription('Verified role').setRequired(true)).addRoleOption(o=>o.setName('unverified_role').setDescription('Optional unverified role').setRequired(false)))
  .addSubcommand(s=>s.setName('autorole').setDescription('Set autorole').addRoleOption(o=>o.setName('role').setDescription('Role').setRequired(true))),
 execute:async i=>{const s=database.getSettings(i.guildId),sub=i.options.getSubcommand();if(sub==='view')return i.reply({embeds:[embed('Server configuration',`\`\`json\n${JSON.stringify(s,null,2)}\n\`\`\n`)],ephemeral:true});const map={welcome:'channel',goodbye:'channel',logs:'channel',moderation:'enabled',automod:'enabled',tickets:'role',autorole:'role'};if(sub==='verification'){s.verification={verifiedRole:i.options.getRole('verified_role').id,unverifiedRole:i.options.getRole('unverified_role')?.id||null};}else{s[sub==='moderation'?'moderationEnabled':sub]=map[sub]==='channel'?i.options.getChannel('channel').id:map[sub]==='role'?i.options.getRole('role').id:i.options.getBoolean('enabled');}database.saveSettings(i.guildId,s);return i.reply({embeds:[ok(`Configuration **${sub}** saved.`)],ephemeral:true})}},
 {data:new SlashCommandBuilder().setName('giveaway').setDescription('Manage giveaways').setDefaultMemberPermissions(PermissionFlagsBits.ManageGuild).addSubcommand(s=>s.setName('start').setDescription('Start giveaway').addIntegerOption(o=>o.setName('duration').setDescription('Seconds').setMinValue(10).setRequired(true)).addIntegerOption(o=>o.setName('winners').setDescription('Winner count').setMinValue(1).setMaxValue(20).setRequired(true)).addStringOption(o=>o.setName('prize').setDescription('Prize').setMaxLength(200).setRequired(true))).addSubcommand(s=>s.setName('end').setDescription('End giveaway').addStringOption(o=>o.setName('message_id').setDescription('Giveaway message ID').setRequired(true))).addSubcommand(s=>s.setName('reroll').setDescription('Reroll giveaway').addStringOption(o=>o.setName('message_id').setDescription('Giveaway message ID').setRequired(true))).addSubcommand(s=>s.setName('list').setDescription('List giveaways')),
 execute:async i=>{const sub=i.options.getSubcommand();if(sub==='list'){const rows=database.db.prepare('SELECT message_id,prize,ends_at,ended FROM giveaways WHERE guild_id=? ORDER BY ends_at DESC LIMIT 20').all(i.guildId);return i.reply({embeds:[embed('Giveaways',rows.length?rows.map(x=>`\`${x.message_id}\` — ${x.prize} — ${x.ended?'ended':`ends <t:${Math.floor(x.ends_at/1000)}:R>`}`).join('\n'):'No giveaways.')],ephemeral:true});}const {finishGiveaway}=await import('../database/index.js');if(sub==='start'){const end=Date.now()+i.options.getInteger('duration')*1000;const msg=await i.channel.send({embeds:[embed('🎉 Giveaway',`Prize: **${i.options.getString('prize')}**\nEnds: <t:${Math.floor(end/1000)}:R>\nClick Enter to participate.`)],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('giveaway:enter').setLabel('Enter').setStyle(ButtonStyle.Success))]});database.db.prepare('INSERT INTO giveaways(message_id,guild_id,channel_id,prize,ends_at,winners) VALUES(?,?,?,?,?,?)').run(msg.id,i.guildId,i.channelId,i.options.getString('prize'),end,i.options.getInteger('winners'));return i.reply({embeds:[ok(`Giveaway started: ${msg}`)],ephemeral:true});}const row=database.giveaway(i.options.getString('message_id'));if(!row||row.guild_id!==i.guildId)return i.reply({embeds:[fail('Giveaway not found.')],ephemeral:true});if(sub==='reroll'&&!row.ended)return i.reply({embeds:[fail('End the giveaway before rerolling.')],ephemeral:true});await finishGiveaway(i.client,row,sub==='reroll');return i.reply({embeds:[ok(`${sub==='end'?'Giveaway ended.':'Winner rerolled.'}`)],ephemeral:true});}},
 {data:new SlashCommandBuilder().setName('tickets').setDescription('Ticket controls').setDefaultMemberPermissions(PermissionFlagsBits.ManageChannels).addSubcommand(s=>s.setName('setup').setDescription('Post ticket panel')).addSubcommand(s=>s.setName('close').setDescription('Close current ticket')),execute:async i=>{if(i.options.getSubcommand()==='setup')return i.reply({embeds:[embed('Support tickets','Click to open a private ticket.')],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('ticket:create').setLabel('Create ticket').setStyle(ButtonStyle.Primary))]});const t=database.db.prepare('SELECT * FROM tickets WHERE channel_id=? AND status=?').get(i.channelId,'open');if(!t)return i.reply({embeds:[fail('This is not an open ticket.')],ephemeral:true});database.db.prepare('UPDATE tickets SET status="closed",closed_at=? WHERE channel_id=?').run(Date.now(),i.channelId);return i.reply({embeds:[ok('Ticket closed.')],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('ticket:close').setLabel('Close ticket').setStyle(ButtonStyle.Danger).setDisabled(true))]})}},
 {data:new SlashCommandBuilder().setName('verification').setDescription('Post verification panel').setDefaultMemberPermissions(admin).addSubcommand(s=>s.setName('setup').setDescription('Post Verify button')),execute:async i=>{const s=database.getSettings(i.guildId);if(!s.verification?.verifiedRole)return i.reply({embeds:[fail('Configure verified role first with `/config verification`.')],ephemeral:true});return i.reply({embeds:[embed('Verification','Click Verify to receive the configured role.')],components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('verification:verify').setLabel('Verify').setStyle(ButtonStyle.Success))]})}},
 {data:new SlashCommandBuilder().setName('owner').setDescription('Owner tools').addStringOption(o=>o.setName('action').setDescription('reload/status/servers/broadcast/shutdown').setRequired(true)).addStringOption(o=>o.setName('message').setDescription('Broadcast text').setRequired(false)),execute:async i=>{if(i.user.id!==process.env.OWNER_ID)return i.reply({embeds:[fail('Owner only.')],ephemeral:true});const a=i.options.getString('action');if(a==='shutdown')return i.reply({embeds:[fail('Shutdown is disabled from arbitrary interactions. Use a controlled process signal.')],ephemeral:true});if(a==='status')return i.reply({embeds:[ok(`Ready: **${i.client.ws.status}**, servers: **${i.client.guilds.cache.size}**`)],ephemeral:true});if(a==='servers')return i.reply({embeds:[ok(i.client.guilds.cache.map(g=>`${g.name} (${g.id})`).join('\n')||'No servers.')],ephemeral:true});if(a==='reload')return i.reply({embeds:[ok('Reload acknowledged; restart the controlled process to apply code changes.')],ephemeral:true});if(a==='broadcast'){const text=i.options.getString('message');if(!text)return i.reply({embeds:[fail('message is required for broadcast.')],ephemeral:true});return i.reply({embeds:[ok('Broadcast confirmation required; no message was sent.')],ephemeral:true});}return i.reply({embeds:[fail('Unknown owner action.')],ephemeral:true})}}
];
export async function loadCommands(client){for(const c of commands)client.commands.set(c.data.name,c)}
export {commands};
