import { Events, ChannelType, PermissionFlagsBits } from 'discord.js';
import { logger } from '../utils/logger.js';
import { fail, embed, ok } from '../utils/embed.js';
import { database, finishGiveaway } from '../database/index.js';
import { isOnCooldown } from '../config.js';
export function registerEvents(client) {
  client.once(Events.ClientReady, c => { logger.info(`Logged in as ${c.user.tag}`); const tick=async()=>{for(const row of database.activeGiveaways()) await finishGiveaway(client,row);}; tick().catch(e=>logger.error('Giveaway expiry failed',e)); setInterval(()=>tick().catch(e=>logger.error('Giveaway expiry failed',e)),30000); });
  client.on(Events.InteractionCreate, async interaction => { try {
    if (interaction.isButton() && isOnCooldown(`${interaction.user.id}:${interaction.customId}`, 1200)) return interaction.reply({embeds:[fail('Please wait a moment.')],ephemeral:true});
    if (interaction.isButton() && interaction.customId === 'giveaway:enter') { if(database.addGiveawayEntry(interaction.message.id,interaction.user.id)) return interaction.reply({embeds:[ok('You entered the giveaway.')],ephemeral:true}); return interaction.reply({embeds:[fail('You are already entered, or this giveaway has ended.')],ephemeral:true}); }
    if (interaction.isButton() && interaction.customId === 'verification:verify') { const s=database.getSettings(interaction.guildId), role=interaction.guild.roles.cache.get(s.verification?.verifiedRole); if(!role)return interaction.reply({embeds:[fail('Verification is not configured.')],ephemeral:true}); if(s.verification.unverifiedRole) await interaction.member.roles.remove(s.verification.unverifiedRole).catch(()=>{}); await interaction.member.roles.add(role); return interaction.reply({embeds:[ok('You are verified.')],ephemeral:true}); }
    if (interaction.isButton() && interaction.customId === 'ticket:create') { const existing=database.db.prepare('SELECT channel_id FROM tickets WHERE guild_id=? AND creator_id=? AND status=?').get(interaction.guildId,interaction.user.id,'open'); if(existing)return interaction.reply({embeds:[fail(`You already have an open ticket: <#${existing.channel_id}>`)],ephemeral:true}); const s=database.getSettings(interaction.guildId), staff=s.tickets; const overwrites=[{id:interaction.guild.roles.everyone.id,deny:[PermissionFlagsBits.ViewChannel]},{id:interaction.user.id,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages]}]; if(staff)overwrites.push({id:staff,allow:[PermissionFlagsBits.ViewChannel,PermissionFlagsBits.SendMessages]}); const channel=await interaction.guild.channels.create({name:`ticket-${interaction.user.username}`.slice(0,90),type:ChannelType.GuildText,permissionOverwrites:overwrites}); database.db.prepare('INSERT INTO tickets(guild_id,channel_id,creator_id,created_at) VALUES(?,?,?,?)').run(interaction.guildId,channel.id,interaction.user.id,Date.now()); await channel.send({content:`${interaction.user}`,embeds:[embed('Ticket opened','Staff can use `/tickets close`.')],components:[{type:1,components:[{type:2,custom_id:'ticket:close',label:'Close ticket',style:4}]}]}); return interaction.reply({embeds:[ok(`Ticket created: ${channel}`)],ephemeral:true}); }
    if (interaction.isButton() && interaction.customId === 'ticket:close') { if(!interaction.memberPermissions?.has(PermissionFlagsBits.ManageChannels))return interaction.reply({embeds:[fail('Manage Channels permission required.')],ephemeral:true}); const t=database.db.prepare('SELECT * FROM tickets WHERE channel_id=? AND status=?').get(interaction.channelId,'open');if(!t)return interaction.reply({embeds:[fail('This is not an open ticket.')],ephemeral:true});database.db.prepare('UPDATE tickets SET status="closed",closed_at=? WHERE channel_id=?').run(Date.now(),interaction.channelId);await interaction.update({embeds:[ok('Ticket closed.')],components:[]});return interaction.channel.permissionOverwrites.edit(t.creator_id,{SendMessages:false}).catch(()=>{}); }
    if (!interaction.isChatInputCommand()) return; const command=client.commands.get(interaction.commandName); if(!command)return interaction.reply({embeds:[fail('Unknown command.')],ephemeral:true}); await command.execute(interaction);
  } catch(error) { logger.error('Interaction failed',error); const response={embeds:[fail('Something went wrong while handling that interaction.')],ephemeral:true}; if(interaction.replied||interaction.deferred)await interaction.followUp(response);else await interaction.reply(response); } });
  client.on(Events.GuildMemberAdd, async member => { const s=database.getSettings(member.guild.id); if(s.autorole)await member.roles.add(s.autorole).catch(e=>logger.error('Autorole failed',e)); if(s.verification?.unverifiedRole)await member.roles.add(s.verification.unverifiedRole).catch(()=>{}); if(s.welcome){const c=member.guild.channels.cache.get(s.welcome);if(c)await c.send(`Welcome ${member} to **${member.guild.name}**!`).catch(()=>{});} });
  client.on(Events.GuildMemberRemove, async member => { const s=database.getSettings(member.guild.id),c=member.guild.channels.cache.get(s.goodbye);if(c)await c.send(`**${member.user?.tag||'A member'}** left the server.`).catch(()=>{}); });
  client.on(Events.MessageCreate, async message => { if(message.author.bot||!message.guild)return; const s=database.getSettings(message.guild.id);if(s.automod===true&&/(discord\.gg\/|@everyone|@here)/i.test(message.content)){await message.delete().catch(()=>{});const log=message.guild.channels.cache.get(s.logs);if(log)log.send(`Automod removed a message from ${message.author} in ${message.channel}.`).catch(()=>{});} });
  client.on(Events.Error,error=>logger.error('Discord client error',error));
}
